#!/bin/bash
# run static analysis for a range of dates, outputting diffs for each new
# revision.

start_date=${1:-$(date +%Y-%m-%d -d yesterday)}
end_date=${2:-$(date +%Y-%m-%d)}

tags=$(git tag -l 'wt-*' | \
       awk '($1 >= "wt-'$start_date'") && ($1 <= "wt-'$end_date'")')

last_tag=''
for tag in $tags; do
	mkdir -p check
	out=check/check.$tag
	if [[ ! -e $out ]]; then
		echo "Check $tag"
		git checkout $tag
		make C=2 M=net/wireless 2>&1 | grep ':' | grep -v 'bio' >>$out
		make C=2 M=net/mac80211 2>&1 | grep ':' | grep -v 'bio' >>$out
		make C=2 M=drivers/net/wireless 2>&1 | grep ':' | grep -v 'bio' >>$out
	fi
	if [[ ! -z $last_tag ]]; then
		echo "*** $tag ***"
		diff_out=${out}.diff
		last_out=check/check.$last_tag
		diff -u <(sed 's/:[0-9]*//g' $last_out) \
			<(sed 's/:[0-9]*//g' $out) | tee $diff_out
	fi
	last_tag=$tag
done
git checkout master

