#!/bin/bash
# push out today's tag (if present)

# customize GIT_SSH if needed (for askpass etc)
if [[ ! -z $WT_SSH ]]; then
	export GIT_SSH=$WT_SSH
	export GPG_TTY=$(tty)
fi

today=`date +%Y-%m-%d`
tag=${1:-wt-$today}
shift
remotes="$*"

if [ -z $remotes ]; then
	remotes="origin github"
fi

git show-ref -s $tag > /dev/null
ret=$?
if [[ $ret -ne 0 ]]; then
	echo "Tag $tag not found."
	exit 1
fi

for remote in $remotes; do
	echo "Pushing to $remote..."
	git push $remote +master
	git push $remote $tag

	# Also push any new linus tags
	linus=$(cat .wtref.linus)
	git push $remote $linus
done
