#!/bin/bash
# push out today's tag (if present)

# customize GIT_SSH if needed (for askpass etc)
if [[ ! -z $WT_SSH ]]; then
	export GIT_SSH=$WT_SSH
fi

today=`date +%Y-%m-%d`
remote=${1:-origin}
datestr=${2:-$today}

tag=wt-$datestr
git show-ref -s $tag > /dev/null
ret=$?
if [[ $ret -ne 0 ]]; then
	echo "Tag $tag not found."
	exit 1
fi
git push $remote +master
git push $remote $tag

# Also push any new linus tags
linus=$(cat .wtref.linus)
git push $remote $linus
