#!/bin/bash
# push out today's tag (if present)

# customize GIT_SSH if needed (for askpass etc)
if [[ ! -z $WT_SSH ]]; then
	export GIT_SSH=$WT_SSH
fi

remote=${1:-origin}
tag=wt-`date +%Y-%m-%d`
git show-ref -s $tag > /dev/null
ret=$?
if [[ $ret -ne 0 ]]; then
	echo "Tag $tag not found."
	exit 1
fi
git push $remote +master
git push $remote $tag
